specieslist="Amel Bter Hsal Cflo Pdom Nvit Dmel Atha Bdis Osat Xtro Drer Btau Mmus"

all:
	@ printf "Species\tAsAnnotated\tRandom\n"
	@ for species in "$(specieslist)"; do ./perc-zilocus.sh $$species; done
